name: 'Setup'
description: 'Setup Ruby on Rails project'
runs:
  using: "composite"
  steps:
    - name: Add SSH key to chekout a private repo
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.REPO_SSH_KEY }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'
    - name: Install packages
      shell: bash
      run: |
        yarn install --pure-lockfile
        yarn build:css
        yarn build:js
